site_name: My Docs
site_url: http://docs.TTT.TT/mkdocs
repo_url: https://github.com/7hUd41/mkdocs-config
repo_name: 7hUd41/mkdocs-config
edit_uri: edit/main/



theme:
  name: material
  custom_dir: overrides
  icon:
    # repo: fontawesome/brands/git
    repo: octicons/git-merge-24
    edit: material/pencil 
    view: material/eye
  features:
    - content.action.edit
    - content.action.view


extra_css:
  - css/style.css
extra_javascript:
  - js/script.js

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-committers:
      repository: 7hUd41/mkdocs-config

